analytics: {}
color:
  brandColors:
    - '#0A0A12'
    - '#7B585C'
    - '#533B39'
    - '#C7A9B3'
    - '#953A41'
  brandStrength: 0.51098
  lightness: 0.505912
  rhythmicContrast: 0.514358
  saturation: 0.516047
cta: {}
layout_spectrum: 0.891047
name: WILL BOWDEN
opengraph: {}
purpose: []
typography_spectrum: 0.789696
